// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUUAZ34WjFqgA5JwpZgxVW1eaJLyAWvqE',
    appId: '1:185561057536:web:130b2d46124801d1a24be5',
    messagingSenderId: '185561057536',
    projectId: 'diplom-ea994',
    authDomain: 'diplom-ea994.firebaseapp.com',
    storageBucket: 'diplom-ea994.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKgIXuMfSGNoy7OwfuKBw14ZYgL4C53tE',
    appId: '1:185561057536:android:bdb0f2689397c68ba24be5',
    messagingSenderId: '185561057536',
    projectId: 'diplom-ea994',
    storageBucket: 'diplom-ea994.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJw_-a10my-h6Tg98MQdJzyLwusuzqj1Y',
    appId: '1:185561057536:ios:1465c20d5bc5e4eba24be5',
    messagingSenderId: '185561057536',
    projectId: 'diplom-ea994',
    storageBucket: 'diplom-ea994.firebasestorage.app',
    iosBundleId: 'com.example.diplom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJw_-a10my-h6Tg98MQdJzyLwusuzqj1Y',
    appId: '1:185561057536:ios:1465c20d5bc5e4eba24be5',
    messagingSenderId: '185561057536',
    projectId: 'diplom-ea994',
    storageBucket: 'diplom-ea994.firebasestorage.app',
    iosBundleId: 'com.example.diplom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUUAZ34WjFqgA5JwpZgxVW1eaJLyAWvqE',
    appId: '1:185561057536:web:393729a95d6c0099a24be5',
    messagingSenderId: '185561057536',
    projectId: 'diplom-ea994',
    authDomain: 'diplom-ea994.firebaseapp.com',
    storageBucket: 'diplom-ea994.firebasestorage.app',
  );
}
